- pattern: "^app.*"
  role: "Application Server"
- pattern: "^db.*"
  role: "Database Server"
- pattern: "^jobs.*"
  role: "Job Server"
- pattern: "^memcache.*"
  role: "Memcache Server"
- pattern: "^redis.*"
  role: "Redis Server"
- pattern: "search"
  role: "Search Server"
