- pattern: "System/Disk/.*/Writes/Utilization/percent"
- pattern: "System/Disk/.*/Reads/Utilization/percent"
- pattern: "System/CPU/System/percent"
- pattern: "System/CPU/User/percent"
- pattern: "System/CPU/IO Wait/percent"
- pattern: "System/Network/eth0/All/bytes/sec"
- pattern: "System/CPU/Stolen/percent"

